# Phase 1

In [2]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [4]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

In [6]:
X

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [7]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [8]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [9]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense


/home/ambarish/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
/home/ambarish/anaconda3/lib/python3.6/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.24.1) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)


In [10]:
# Initialising the ANN
classifier = Sequential()

In [11]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))

/home/ambarish/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  


In [12]:
# Adding the hidden layers
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))

/home/ambarish/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  
/home/ambarish/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
/home/ambarish/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  after removing the cwd from sys.path.


In [13]:
# Adding the output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

/home/ambarish/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  


In [14]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics =['accuracy'])

In [15]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

/home/ambarish/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


Epoch 1/100
8000/8000 [==============================] - 2s 298us/step - loss: 0.6134 - acc: 0.7954
Epoch 2/100
8000/8000 [==============================] - 1s 82us/step - loss: 0.5336 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 82us/step - loss: 0.5119 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 82us/step - loss: 0.5070 - acc: 0.7960
Epoch 5/100
8000/8000 [==============================] - 1s 82us/step - loss: 0.5060 - acc: 0.7960
Epoch 6/100
8000/8000 [==============================] - 1s 91us/step - loss: 0.5060 - acc: 0.7960
Epoch 7/100
8000/8000 [==============================] - 1s 86us/step - loss: 0.5060 - acc: 0.7960
Epoch 8/100
8000/8000 [==============================] - 1s 91us/step - loss: 0.5060 - acc: 0.7960
Epoch 9/100
8000/8000 [==============================] - 1s 93us/step - loss: 0.5060 - acc: 0.7960
Epoch 10/100
8000/8000 [==============================] - 1s 91us/step - loss: 0.5059 - acc: 0.7960
Epoch 11

In [20]:
testdata = pd.DataFrame(X_test)

In [21]:
#testdata

In [22]:
traindata = pd.DataFrame(X_train)

In [23]:
#traindata

In [24]:
Newdata = testdata.append(traindata, ignore_index= True)

In [25]:
#Newdata

In [26]:
new_pred = classifier.predict(Newdata)

In [27]:
output_df = pd.DataFrame(new_pred, columns = ["11"])

In [28]:
#output_df

In [29]:
latest_dataset = pd.concat([Newdata, output_df], axis = 1)

In [30]:
latest_dataset.head()

0         1         2         3         4         5         6  \
0  1.754865 -0.573694 -0.552043 -1.091687 -0.368904  1.044737  0.879303   
1 -0.569844 -0.573694 -1.314903 -1.091687  0.109617 -1.031415  0.429722   
2 -0.569844  1.743090  0.571630 -1.091687  0.301026  1.044737  0.308583   
3 -0.569844 -0.573694  1.416961  0.916013 -0.656016 -0.339364  0.575336   
4  1.754865 -0.573694  0.571630  0.916013 -0.081791  0.006661  1.389611   

          7         8         9        10        11  
0 -0.921591  0.642595  0.968738  1.610857  0.204149  
1 -0.921591  0.642595 -1.032270  0.495870  0.204149  
2 -0.921591  0.642595  0.968738 -0.424787  0.204149  
3 -0.921591 -1.556190 -1.032270 -0.187777  0.204149  
4  0.809503  0.642595  0.968738  0.616842  0.204149

In [31]:
X_new = latest_dataset.iloc[:, 11].values
y_new = latest_dataset.iloc[:, 0:11].values

In [32]:
X_new

array([0.20414938, 0.20414938, 0.20414938, ..., 0.20414938, 0.20414938,
       0.20414938], dtype=float32)

In [33]:
X_new1 = X_new.reshape(10000,1)

In [34]:
X_new1

array([[0.20414938],
       [0.20414938],
       [0.20414938],
       ...,
       [0.20414938],
       [0.20414938],
       [0.20414938]], dtype=float32)

In [35]:
X_new_train, X_new_test, y_new_train, y_new_test = train_test_split(X_new1, y_new, test_size = 0.5, random_state= 1)

In [36]:
X_new_train

array([[0.20414938],
       [0.20414938],
       [0.20414938],
       ...,
       [0.20414938],
       [0.20414938],
       [0.20414938]], dtype=float32)

In [37]:
y_new_train

array([[-0.5698444 ,  1.74309049,  0.56132079, ..., -1.55619021,
         0.9687384 , -1.24327061],
       [-0.5698444 , -0.57369368,  0.32421559, ..., -1.55619021,
         0.9687384 , -0.30068122],
       [ 1.75486502, -0.57369368, -1.21181375, ..., -1.55619021,
        -1.03227043, -0.35827451],
       ...,
       [-0.5698444 ,  1.74309049, -1.84065797, ..., -1.55619021,
         0.9687384 , -0.74475066],
       [-0.5698444 , -0.57369368, -1.57262601, ..., -1.55619021,
        -1.03227043,  0.61915969],
       [-0.5698444 , -0.57369368,  0.47884941, ...,  0.64259497,
        -1.03227043, -0.61529117]])

# Phase 2

# Using Multiple Regression

In [38]:
from sklearn.linear_model import LinearRegression

In [39]:
reg = LinearRegression()

In [40]:
reg.fit(X_new_train, y_new_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [41]:
reg.predict(X_new_test[:1,:])

array([[ 0.03550959, -0.02600604, -0.00343697,  0.00692666,  0.01152036,
         0.01067489,  0.03098869, -0.01345921, -0.02627563, -0.01295662,
        -0.00191848]], dtype=float32)

In [42]:
reg.score(X_new_test, y_new_test)

-0.000905854668215378

In [43]:
X_new_train.shape

(5000, 1)

In [44]:
y_new_train.shape

(5000, 11)

# Using ANN

In [53]:
model = Sequential()
# the shape of one training example is
input_shape = X_new_train[0].shape
model.add(Dense(units=11, activation='relu', input_shape=input_shape))

# Hidden Layers
model.add(Dense(units=11, activation='relu'))
model.add(Dense(units=11, activation='relu'))
model.add(Dense(units=11, activation='relu'))
model.add(Dense(units=11, activation='relu'))
model.add(Dense(units=11, activation='relu'))
model.add(Dense(units=11, activation='relu'))
model.add(Dense(units=11, activation='relu'))
model.add(Dense(units=11, activation='relu'))
model.add(Dense(units=11, activation='relu'))
model.add(Dense(units=11, activation='relu'))
model.add(Dense(units=11, activation='relu'))
model.add(Dense(units=11, activation='relu'))
model.add(Dense(units=11, activation='relu'))
model.add(Dense(units=11, activation='relu'))
model.add(Dense(units=11, activation='relu'))
model.add(Dense(units=11, activation='relu'))
model.add(Dense(units=11, activation='relu'))
model.add(Dense(units=11, activation='relu'))
model.add(Dense(units=11, activation='relu'))
model.add(Dense(units=11, activation='relu'))
model.add(Dense(units=11, activation='relu'))
model.add(Dense(units=11, activation='relu'))
model.add(Dense(units=11, activation='relu'))
model.add(Dense(units=11, activation='relu'))
model.add(Dense(units=11, activation='relu'))
model.add(Dense(units=11, activation='relu'))
model.add(Dense(units=11, activation='relu'))
model.add(Dense(units=11, activation='relu'))
model.add(Dense(units=11, activation='relu'))
model.add(Dense(units=11, activation='relu'))
model.add(Dense(units=11, activation='relu'))
model.add(Dense(units=11, activation='relu'))
model.add(Dense(units=11, activation='relu'))

# Output Layers
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))
model.add(Dense(units=11, activation='softmax'))

# Compile the ann
model.compile(optimizer='rmsprop', loss='binary_crossentropy', 
metrics=['accuracy'])

In [54]:
model.fit(X_new_train, y_new_train, batch_size = 10, epochs=50)

Epoch 1/50
5000/5000 [==============================] - 4s 856us/step - loss: 0.0976 - acc: 0.0000e+00
Epoch 2/50
5000/5000 [==============================] - 2s 372us/step - loss: 0.0963 - acc: 0.0000e+00
Epoch 3/50
5000/5000 [==============================] - 2s 409us/step - loss: 0.0951 - acc: 0.0000e+00
Epoch 4/50
5000/5000 [==============================] - 2s 416us/step - loss: 0.0940 - acc: 0.0000e+00
Epoch 5/50
5000/5000 [==============================] - 2s 369us/step - loss: 0.0929 - acc: 0.0000e+00
Epoch 6/50
5000/5000 [==============================] - 2s 371us/step - loss: 0.0919 - acc: 0.0000e+00
Epoch 7/50
5000/5000 [==============================] - 2s 372us/step - loss: 0.0910 - acc: 0.0000e+00
Epoch 8/50
5000/5000 [==============================] - 2s 372us/step - loss: 0.0902 - acc: 0.0000e+00
Epoch 9/50
5000/5000 [==============================] - 2s 370us/step - loss: 0.0893 - acc: 0.0000e+00
Epoch 10/50
5000/5000 [==============================] - 2s 389us/step - 

In [47]:
model.predict(X_new_test[0, :])

array([[4.6864522e-01, 6.3890555e-05, 5.1614977e-03, 2.4818735e-02,
        4.9930815e-02, 4.3761488e-02, 4.0149298e-01, 5.4135144e-04,
        3.0304139e-04, 8.3392480e-04, 4.4470006e-03]], dtype=float32)